// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEnORs8SXVQDO-RLApI4MT3eWhRu8UG0',
    appId: '1:234359654969:web:af7b9f1b540c370cbd1be8',
    messagingSenderId: '234359654969',
    projectId: 'mikhaelvito-ell',
    authDomain: 'mikhaelvito-ell.firebaseapp.com',
    storageBucket: 'mikhaelvito-ell.firebasestorage.app',
    measurementId: 'G-BCB3D7E622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj7I4wNzaFDTdQ_6D6nBkrRWypVcV8XPU',
    appId: '1:234359654969:android:dd5bdfbd888bd18dbd1be8',
    messagingSenderId: '234359654969',
    projectId: 'mikhaelvito-ell',
    storageBucket: 'mikhaelvito-ell.firebasestorage.app',
  );
}
