// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ19O7rUXRJMMGhTjyNk5b4fwkjv9BF6E',
    appId: '1:451306829653:web:2ca62e6df9a5c228d421dc',
    messagingSenderId: '451306829653',
    projectId: 'cepu-7935f',
    authDomain: 'cepu-7935f.firebaseapp.com',
    storageBucket: 'cepu-7935f.firebasestorage.app',
    measurementId: 'G-6NRRFKXTV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTb_VlYvhvbjQRc3F8NnOhPoNJu-z2ew',
    appId: '1:451306829653:android:9aaacb2a1307bc6dd421dc',
    messagingSenderId: '451306829653',
    projectId: 'cepu-7935f',
    storageBucket: 'cepu-7935f.firebasestorage.app',
  );
}
