// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxY_r00-e1n_B2bHFcP63llfR7e8Au_Fs',
    appId: '1:1011427223301:web:f729c79e02db500d6b396c',
    messagingSenderId: '1011427223301',
    projectId: 'daftarbelanja-2f436',
    authDomain: 'daftarbelanja-2f436.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-2f436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-2f436.firebasestorage.app',
    measurementId: 'G-FEJMXD5ZSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EuNbmQI_F9tv8Yg5_1kyOW7qXOHmDfM',
    appId: '1:1011427223301:android:adbcee9c1f8dc0a76b396c',
    messagingSenderId: '1011427223301',
    projectId: 'daftarbelanja-2f436',
    databaseURL: 'https://daftarbelanja-2f436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-2f436.firebasestorage.app',
  );
}
